#!/usr/bin/env python3
"""Compare an independent expectation with hash-linked Lago evidence."""

from __future__ import annotations

import argparse
import hashlib
import json
from decimal import Decimal, InvalidOperation
from pathlib import Path

from extract_actual import ExtractionError, extract, reject_constant as reject_source_constant

FIELDS = ("quantity", "unit_price", "subtotal", "discounts", "credits", "tax", "total")


def reject_constant(name: str) -> object:
    raise ValueError(f"non-finite JSON value {name} is not allowed in a money test")


def load(path: Path, max_bytes: int) -> dict[str, object]:
    size = path.stat().st_size
    if size > max_bytes:
        raise ValueError(f"{path} is {size} bytes; limit is {max_bytes} bytes")
    value = json.loads(path.read_text(encoding="utf-8"), parse_constant=reject_constant)
    if not isinstance(value, dict):
        raise ValueError(f"{path} must contain an object")
    return value


def evidence_errors(
    actual: dict[str, object], source: Path | None, max_bytes: int
) -> list[dict[str, str]]:
    errors: list[dict[str, str]] = []
    evidence = actual.get("_evidence")
    if not isinstance(evidence, dict) or evidence.get("generated_by") != "extract_actual.py":
        errors.append(
            {
                "field": "evidence",
                "error": "actual must be generated by extract_actual.py, not hand-written",
            }
        )
        return errors
    if source is None:
        errors.append(
            {
                "field": "evidence",
                "error": "provide --actual-source so the preserved Lago payload can be hash-verified",
            }
        )
        return errors
    try:
        size = source.stat().st_size
        if size > max_bytes:
            raise ValueError(f"actual source is {size} bytes; limit is {max_bytes} bytes")
        raw = source.read_bytes()
        digest = hashlib.sha256(raw).hexdigest()
        payload = json.loads(raw, parse_constant=reject_source_constant)
        regenerated = extract(payload, digest)
    except (OSError, UnicodeError, json.JSONDecodeError, ExtractionError, ValueError) as error:
        errors.append({"field": "evidence", "error": f"cannot read actual source: {error}"})
        return errors
    if evidence.get("source_sha256") != digest:
        errors.append(
            {
                "field": "evidence",
                "error": "actual does not match the preserved Lago payload hash",
            }
        )
    if actual != regenerated:
        errors.append(
            {
                "field": "evidence",
                "error": "actual differs from a fresh extraction of the preserved Lago payload",
            }
        )
    return errors


def decimal_field(payload: dict[str, object], field: str) -> Decimal:
    try:
        value = Decimal(str(payload[field]))
    except (KeyError, InvalidOperation) as error:
        raise ValueError(str(error)) from error
    if not value.is_finite():
        raise ValueError("value must be finite")
    return value


def formula_error(payload: dict[str, object], label: str) -> dict[str, str] | None:
    try:
        subtotal = decimal_field(payload, "subtotal")
        discounts = decimal_field(payload, "discounts")
        credits = decimal_field(payload, "credits")
        tax = decimal_field(payload, "tax")
        total = decimal_field(payload, "total")
    except ValueError:
        return None
    calculated = subtotal - discounts - credits + tax
    if calculated != total:
        return {
            "field": f"{label}_formula",
            "error": "subtotal - discounts - credits + tax does not equal total",
            "calculated": str(calculated),
            "total": str(total),
        }
    return None


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("expected", type=Path)
    parser.add_argument("actual", type=Path)
    parser.add_argument(
        "--actual-source",
        type=Path,
        help="preserved Lago API payload used to generate actual",
    )
    parser.add_argument("--max-bytes", type=int, default=10_000_000)
    args = parser.parse_args()
    try:
        expected, actual = load(args.expected, args.max_bytes), load(args.actual, args.max_bytes)
    except (OSError, UnicodeError, json.JSONDecodeError, ValueError) as error:
        print(json.dumps({"status": "FAIL", "mismatches": [{"field": "input", "error": str(error)}]}, indent=2))
        return 1

    mismatches: list[dict[str, str]] = evidence_errors(
        actual, args.actual_source, args.max_bytes
    )
    if expected.get("currency") in (None, "") or actual.get("currency") in (None, ""):
        mismatches.append({"field": "currency", "error": "currency is required in both files"})
    elif expected.get("currency") != actual.get("currency"):
        mismatches.append(
            {
                "field": "currency",
                "expected": str(expected.get("currency")),
                "actual": str(actual.get("currency")),
            }
        )
    for field in FIELDS:
        try:
            left, right = decimal_field(expected, field), decimal_field(actual, field)
        except ValueError as error:
            mismatches.append({"field": field, "error": str(error)})
            continue
        if left != right:
            mismatches.append(
                {
                    "field": field,
                    "expected": str(left),
                    "actual": str(right),
                    "delta": str(right - left),
                }
            )
    for payload, label in ((expected, "expected"), (actual, "actual")):
        error = formula_error(payload, label)
        if error:
            mismatches.append(error)
    print(json.dumps({"status": "PASS" if not mismatches else "FAIL", "mismatches": mismatches}, indent=2))
    return 0 if not mismatches else 1


if __name__ == "__main__":
    raise SystemExit(main())
